name: Lint

on: [push]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install flake8
        run: python3 -m pip install flake8
      - name: Run flake8
        run: flake8
