name: Run pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: A job to run pytest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install package
      run: |
        python3 -m pip install pytest
        python3 -m pip install .
    - name: Run pytest
      run: pytest -v -s ./test/other
